FROM node:16-alpine3.12

RUN apk update && apk add --no-cache curl git jq rsync openssh-client

RUN mkdir -p ~/.ssh && chmod 700 ~/.ssh

RUN curl -L https://github.com/gohugoio/hugo/releases/download/v0.91.1/hugo_0.91.1_Linux-64bit.tar.gz | tar -xz && mv hugo /usr/local/bin/hugo

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

COPY ./ ./

RUN git submodule update --init --recursive

CMD npm run dev
