version: '3.9'

services:
  web:
    build:
      context: '.' 
      target: hugo_local
    ports:
      - 1313:1313
    volumes:
      - './:/src'
    depends_on:
      - imgproxy
    networks:
      - internal

  # https://docs.imgproxy.net/configuration
  imgproxy:
    image: registry.pod.cvut.cz/cache/darthsim/imgproxy:v3.20
    environment:
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: /images
      IMGPROXY_ALLOWED_SOURCES: 'local://,https://plik.pod.cvut.cz/'
      IMGPROXY_DEVELOPMENT_ERRORS_MODE: true
      IMGPROXY_PREFERRED_FORMATS: 'avif, webp, jpeg, png'
      IMGPROXY_ENABLE_CLIENT_HINTS: true
      IMGPROXY_ENABLE_WEBP_DETECTION: true
      IMGPROXY_ENABLE_AVIF_DETECTION: true
      IMGPROXY_ONLY_PRESETS: true
      IMGPROXY_MAX_SRC_RESOLUTION: 40
      IMGPROXY_PRESETS: rt_fill=rt:fill,rt_fit=rt:fit,t_100=w:150/h:150,t_250=w:250/h:250,t_480=w:480/h:480,t_800=w:800/h:800,t_1200=w:1200/h:1200,t_1500=w:1500/h:1500,t_2000=w:2000/h:2000
    volumes:
      - ./assets/images:/images
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - internal

networks:
  internal:
