services:
  web:
    build:
      context: '.' 
      target: hugo
    stop_grace_period: 2s
    ports:
      - '1313:1313'
    volumes:
      - './:/src'
    depends_on:
      - imgproxy
    networks:
      - internal

  # https://docs.imgproxy.net/configuration
  imgproxy:
    image: registry.pod.cvut.cz/cache/darthsim/imgproxy:v3.27
    environment:
      IMGPROXY_ALLOWED_SOURCES: 'https://plik.pod.cvut.cz/,https://s3.pod.cvut.cz/'
      IMGPROXY_DEVELOPMENT_ERRORS_MODE: true
      IMGPROXY_PREFERRED_FORMATS: 'avif, jxl, webp, jpeg, png'
      IMGPROXY_ENABLE_CLIENT_HINTS: true
      IMGPROXY_AUTO_WEBP: true
      IMGPROXY_AUTO_AVIF: true
      IMGPROXY_AUTO_JXL: true
      IMGPROXY_ONLY_PRESETS: true
      IMGPROXY_MAX_SRC_RESOLUTION: 40
      IMGPROXY_PRESETS: rt_fill=rt:fill/g:sm,rt_fit=rt:fit,t_250=w:250/h:250,t_480=w:480/h:480,t_800=w:800/h:800,t_1200=w:1200/h:1200,t_1500=w:1500/h:1500,raw=raw:true
      IMGPROXY_DOWNLOAD_BUFFER_SIZE: 5242880
      IMGPROXY_FREE_MEMORY_INTERVAL: 5
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - internal

networks:
  internal:
