FROM klakegg/hugo:0.111.3-ext-alpine-ci AS build

ARG hugo_env=production
ENV HUGO_ENV=${hugo_env}

RUN apk add jq

COPY ./ ./

RUN git submodule update --init --recursive && \
    ./scripts/fetch_contacts.sh && \
    hugo

FROM nginx:mainline-alpine AS deploy

COPY --from=build /src/public /usr/share/nginx/html
