web:
  container:
    image: registry.pod.cvut.cz/internal/pod-o-lee/main-web-prod
  service:
    ports:
      - name: http
        port: 80
        nodePort: 30810

imgproxy:
  resources:
    service:
      nodePort: 30820
    deployment:
      replicas:
        default: 2
