apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: websites
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-pod
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-pod
    spec:
      containers:
        - name: {{ .Release.Name }}-container
          image: "{{ .Values.containerImage }}:{{ .Values.containerTag }}"
          imagePullPolicy: {{ .Values.containerPullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.servicePort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
