apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ default .port .targetPort }}
      {{ if .nodePort }}nodePort: {{ .nodePort }}{{ end }}
    {{- end }}
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
